# Cursor BugBot Configuration for Blit-Tech
# https://docs.cursor.com/context/bugbot

# Enable BugBot for this repository
enabled: true

# Review settings
review:
  # Automatically review PRs
  auto_review: true

  # Focus areas for code review
  focus:
    - performance
    - type_safety
    - security
    - best_practices

  # File patterns to always review
  include:
    - 'src/**/*.ts'
    - 'examples/**/*.ts'
    - '**/*.wgsl'

  # File patterns to skip
  exclude:
    - 'node_modules/**'
    - 'dist/**'
    - '*.min.js'
    - '*.d.ts'

# Project-specific rules
rules:
  # CRITICAL: No emoji anywhere
  no_emoji:
    enabled: true
    severity: error
    message: 'Emoji are not allowed in this project. Use plain text instead.'
    patterns:
      - "[\U0001F300-\U0001F9FF]" # Most emoji ranges
      - "[\u2600-\u26FF]" # Misc symbols
      - "[\u2700-\u27BF]" # Dingbats

  # Integer coordinates for rendering
  integer_coordinates:
    enabled: true
    severity: warning
    message: 'Use Vector2i/Rect2i for coordinates. Avoid floating-point positions.'

  # Avoid any type
  no_any:
    enabled: true
    severity: warning
    message: "Avoid 'any' type. Use proper types or 'unknown'."

  # Type imports
  type_imports:
    enabled: true
    severity: warning
    message: "Use 'import type' for type-only imports."

  # Performance in hot paths
  performance:
    enabled: true
    severity: warning
    check_patterns:
      - pattern: 'new (Vector2i|Rect2i|Color32)'
        in_functions: ['update', 'render', 'draw.*']
        message: 'Avoid object creation in render/update loops. Pre-allocate or reuse objects.'

# WebGPU-specific checks
webgpu:
  # Check for proper resource cleanup
  resource_cleanup:
    enabled: true
    severity: warning
    message: 'GPU resources should be destroyed when no longer needed.'

  # Buffer management
  buffer_checks:
    enabled: true
    severity: warning
    message: 'Check buffer capacity before writing. Use pre-allocated buffers.'

  # Texture formats
  texture_format:
    enabled: true
    preferred_format: 'rgba8unorm'
    message: "Use 'rgba8unorm' for standard textures, 'r8uint' for palette indices."

# Code style (aligned with Biome/ESLint config)
style:
  indent: 4
  max_line_length: 120
  quotes: single
  semicolons: always
  trailing_commas: all

# Documentation requirements
documentation:
  require_jsdoc:
    enabled: true
    for:
      - public_functions
      - public_classes
      - public_interfaces
      - exported_types
    severity: warning

# Commit message rules
commits:
  # Conventional commits format (required)
  format: conventional
  required: true

  # No emoji in commit messages
  no_emoji: true

  # Signed-off-by required (DCO)
  signed_off_by:
    required: true
    message: "Commits must include 'Signed-off-by' line. Use 'git commit -s'."

  # AI co-authorship trailer
  ai_trailer:
    required_when_ai_assisted: true
    format: 'Co-Authored-By: <AI Name> <email>'
    examples:
      - 'Co-Authored-By: Claude <noreply@anthropic.com>'
      - 'Co-Authored-By: GitHub Copilot <copilot@github.com>'
    message: 'AI-assisted commits must include Co-Authored-By trailer.'

  # Allowed types (from commitlint.config.js)
  types:
    - feat # New feature
    - fix # Bug fix
    - docs # Documentation only
    - style # Formatting, no code change
    - refactor # Code restructuring
    - perf # Performance improvement
    - test # Adding or updating tests
    - build # Build system or dependencies
    - ci # CI configuration
    - chore # Maintenance tasks
    - revert # Reverting previous commit

  # Header length limit (from commitlint.config.js)
  header_max_length: 100

  # Suggested scopes (optional but encouraged for clarity)
  suggested_scopes:
    - renderer # Rendering system
    - camera # Camera system
    - assets # Asset loading
    - api # Public API (BT namespace)
    - utils # Utility classes
    - examples # Example projects
    - ci # CI/CD configuration
    - docs # Documentation

# PR description requirements
pull_requests:
  require_description: true
  min_description_length: 50
  no_emoji: true

# Context for AI understanding
context:
  project_type: 'WebGPU game engine'
  language: 'TypeScript'
  framework: 'Custom (Vite build)'
  key_concepts:
    - 'BT namespace is the public API'
    - 'IBlitTechGame interface for game lifecycle'
    - 'Vector2i/Rect2i for integer coordinates'
    - 'Color32 for 32-bit RGBA colors'
    - 'Dual render pipeline (primitives + sprites)'
    - 'Batched rendering for performance'
    - 'Future: VGA Mode 13h palette system'

  performance_sensitive:
    - 'render() method - called every frame'
    - 'update() method - called at 60 FPS'
    - 'Renderer.drawSprite() - hot path'
    - 'Buffer uploads - minimize per frame'

  architecture_notes:
    - 'BTAPI is internal singleton - never expose directly'
    - 'Asset classes have lazy GPU resource creation'
    - 'Textures use nearest-neighbor sampling for pixel-perfect rendering'
    - 'Primitives and sprites use separate WebGPU pipelines'
