import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const CONTENT_DIR = fileURLToPath(new URL('../../content/', import.meta.url));
const DESCRIPTION_MAX_LENGTH = 160;

// Hand-authored pages, per packages/website/CLAUDE.md's "What is hand-authored and what is generated" section.
// content/blog/** is added dynamically below via listBlogPosts(); everything else hand-authored is a fixed,
// known set, so it is listed explicitly rather than globbed.
//
// content/docs/<section>/<topic>.mdx is deliberately NOT included: those pages are generated by
// scripts/sync-docs-from-engine.mjs, and their description comes from the `subtitle` field in
// packages/blit386/docs/_sitemap.json. A length violation there is not fixable by editing anything under
// content/ - the fix belongs in the engine package's sitemap manifest - so folding those pages into this
// assertion would point a contributor at the wrong repository and the wrong file. A guard for the sitemap's
// own subtitles, if wanted, belongs in packages/blit386 against _sitemap.json directly, not here.
const HAND_AUTHORED_PAGES = [
    'index.mdx',
    'showcase.mdx',
    'community.mdx',
    'mcp-server.mdx',
    'docs/index.mdx',
    'docs/getting-started.mdx',
    'docs/faq.mdx',
];

const listBlogPosts = async () => {
    const entries = await readdir(`${CONTENT_DIR}blog/`);
    return entries.filter((name) => name.endsWith('.mdx')).map((name) => `blog/${name}`);
};

/**
 * Decodes a quoted YAML inline scalar (`"..."` or `'...'`), unescaping the handful of escapes this repo's
 * frontmatter could plausibly use. Returns `null` when `raw` isn't quoted, so callers can fall back to
 * treating it as a plain scalar.
 *
 * @param {string} raw
 * @returns {string | null}
 */
const decodeQuotedScalar = (raw) => {
    if (raw.length >= 2 && raw.startsWith('"') && raw.endsWith('"')) {
        /** @type {Record<string, string>} */
        const escapes = { '"': '"', '\\': '\\', n: '\n', t: '\t' };
        return raw.slice(1, -1).replace(/\\(["\\nt])/g, (_match, escaped) => escapes[escaped] ?? escaped);
    }

    if (raw.length >= 2 && raw.startsWith("'") && raw.endsWith("'")) {
        return raw.slice(1, -1).replace(/''/g, "'");
    }

    return null;
};

// `|` (literal) keeps line breaks; `>` (folded) joins with spaces, same as a bare multi-line plain scalar.
// The chomping indicator (`-`/`+`) and indentation indicator (`1`-`9`) are each optional and, per the YAML
// spec, may appear in either order (`|2-` and `|-2` are both valid) - accepted but not otherwise acted on,
// since this guard only measures rendered length and continuation lines are already stripped of leading
// indentation by trimming.
const BLOCK_SCALAR_PATTERN = /^([|>])(?:[1-9][+-]?|[+-][1-9]?|[+-]?)$/;

/**
 * Extracts frontmatter fields from an MDX file's leading `---` block. A value can be a quoted scalar, a
 * block scalar (`|` literal or `>` folded), or - as this repo's authors write longer plain descriptions -
 * a bare `key:` followed by indented continuation lines, which YAML folds into one space-joined string.
 *
 * Deliberately not general-purpose YAML: no trailing `# comment` stripping, anchors, tags, or flow
 * collections. None of that appears in this repo's frontmatter (verified against every hand-authored page
 * this guard reads) and adding support for syntax nothing here uses would just be more surface for this
 * parser to get wrong. Reach for a real YAML parser instead of extending this one if that ever changes.
 *
 * @param {string} contents
 * @returns {Record<string, string>}
 */
const parseFrontmatter = (contents) => {
    const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(contents);
    if (!match) return {};

    /** @type {Record<string, string>} */
    const fields = {};
    /** @type {string | null} */
    let currentKey = null;
    /** @type {string[]} */
    let currentLines = [];
    /** @type {' ' | '\n'} */
    let joiner = ' ';

    const flush = () => {
        if (currentKey) fields[currentKey] = currentLines.join(joiner).trim();
        currentLines = [];
        joiner = ' ';
    };

    for (const line of (match[1] ?? '').split(/\r?\n/)) {
        const keyMatch = /^([A-Za-z_][\w-]*):\s?(.*)$/.exec(line);

        if (keyMatch) {
            flush();
            currentKey = keyMatch[1] ?? null;
            const inlineValue = (keyMatch[2] ?? '').trim();
            const blockScalar = BLOCK_SCALAR_PATTERN.exec(inlineValue);
            const quoted = decodeQuotedScalar(inlineValue);

            if (blockScalar) {
                joiner = blockScalar[1] === '|' ? '\n' : ' ';
                currentLines = [];
            } else if (quoted !== null) {
                currentLines = [quoted];
            } else {
                currentLines = inlineValue ? [inlineValue] : [];
            }
        } else if (currentKey) {
            currentLines.push(line.trim());
        }
    }

    flush();

    return fields;
};

describe('parseFrontmatter', () => {
    test('reads a single-line plain scalar', () => {
        const fields = parseFrontmatter('---\ntitle: X\ndescription: One line\n---\n');
        assert.equal(fields.description, 'One line');
    });

    test('folds a bare multi-line plain scalar into a space-joined string', () => {
        const fields = parseFrontmatter('---\ntitle: X\ndescription:\n  Line one\n  Line two\n---\n');
        assert.equal(fields.description, 'Line one Line two');
    });

    test('decodes a double-quoted inline scalar, including an escaped colon', () => {
        const fields = parseFrontmatter('---\ntitle: X\ndescription: "A: colon example"\n---\n');
        assert.equal(fields.description, 'A: colon example');
    });

    test('decodes a single-quoted inline scalar with an escaped quote', () => {
        const fields = parseFrontmatter("---\ntitle: X\ndescription: 'It''s here'\n---\n");
        assert.equal(fields.description, "It's here");
    });

    test('preserves line breaks in a literal block scalar (|)', () => {
        const fields = parseFrontmatter('---\ntitle: X\ndescription: |\n  Line one\n  Line two\n---\n');
        assert.equal(fields.description, 'Line one\nLine two');
    });

    test('space-joins a folded block scalar (>) like a plain multi-line scalar', () => {
        const fields = parseFrontmatter('---\ntitle: X\ndescription: >\n  Line one\n  Line two\n---\n');
        assert.equal(fields.description, 'Line one Line two');
    });

    test('accepts a literal block scalar header with indent-then-chomp order (|2-)', () => {
        const fields = parseFrontmatter('---\ntitle: X\ndescription: |2-\n  Line one\n  Line two\n---\n');
        assert.equal(fields.description, 'Line one\nLine two');
    });

    test('accepts a folded block scalar header with chomp-then-indent order (>+2)', () => {
        const fields = parseFrontmatter('---\ntitle: X\ndescription: >+2\n  Line one\n  Line two\n---\n');
        assert.equal(fields.description, 'Line one Line two');
    });

    test('returns an empty object when there is no frontmatter block', () => {
        assert.deepEqual(parseFrontmatter('No frontmatter here.'), {});
    });
});

const pages = [...HAND_AUTHORED_PAGES, ...(await listBlogPosts())];

describe('page description length', () => {
    for (const relativePath of pages) {
        test(`content/${relativePath} has a description under ${DESCRIPTION_MAX_LENGTH} characters`, async () => {
            const contents = await readFile(`${CONTENT_DIR}${relativePath}`, 'utf8');
            const { description } = parseFrontmatter(contents);

            assert.ok(description, `content/${relativePath}: description is missing or empty`);

            assert.ok(
                description.length <= DESCRIPTION_MAX_LENGTH,
                `content/${relativePath}: description is ${description.length} characters, exceeds the ${DESCRIPTION_MAX_LENGTH}-character ceiling`,
            );
        });
    }
});
