#!/bin/sh
# SessionStart hook for a scaffolded BLIT386 game. Installs dependencies and runs `blit doctor`
# so a fresh remote/web/cloud session (Claude Code on the web, a Codespace, any ephemeral sandbox)
# works without manual setup. Source: @blit386/kit (generated by `npx blit agents sync`).
#
# Never blocks or fails the session - a SessionStart hook cannot prevent a session from starting
# anyway, so every error here is logged and the script still exits 0.

set -u

PM_INSTALL="${BLIT_PM_INSTALL:-npm install}"

if [ ! -d node_modules ]; then
    echo "[session-start] Installing dependencies with \`$PM_INSTALL\`..."
    if ! sh -c "$PM_INSTALL"; then
        echo "[session-start] Dependency install failed; the session will continue without a warmed toolchain." >&2
        exit 0
    fi
fi

BLIT_BIN="node_modules/.bin/blit"

if [ -x "$BLIT_BIN" ]; then
    "$BLIT_BIN" doctor || true
else
    echo "[session-start] blit CLI not found at $BLIT_BIN; skipping \`blit doctor\`." >&2
fi

exit 0
