#!/bin/sh
# Shell safety hook for Cursor (beforeShellExecution) and Claude Code (PreToolUse).
# Blocks risky destructive git commands. Source: @blit386/kit (generated by `npx blit agents sync`).
# Also symlinked directly as this repo's own .cursor/hooks/shell-safety.sh (dogfooding the same
# dual-protocol script every scaffolded game gets) - see .claude/hooks/shell-safety.sh for the
# Claude-only sibling copy this repo's own PreToolUse hook uses instead.
#
# Protocol:
#   Cursor - JSON on stdout with {"permission":"allow"|"deny"|"ask"}
#   Claude - deny: reason on stderr + exit 2; ask: Claude permissionDecision JSON + exit 0; allow: exit 0
# Detection: Claude stdin includes hook_event_name and/or tool_name.
#
# Policy: which git operations get gated here, and how hard.
#
# Two tiers, split by whether git itself can still recover what the command would discard:
#
#   - Hard block (deny, no override): git reset --hard, git checkout -- / git restore in any form
#     that touches the worktree, and git clean without a no-force dry run. Each of these destroys
#     content with no git object ever created for it - uncommitted worktree/index changes, or
#     untracked files - so nothing is left to recover once the command runs, and no amount of
#     after-the-fact approval changes that. `git restore --staged <path>` (without --worktree) is
#     the one safe form: it only unstages, the worktree file is untouched, so it is not gated.
#
#   - Ask (overridable by an explicit approval): git push --force*, git branch -D, and
#     git stash drop/clear. Each of these can still discard work, but git keeps the underlying
#     commits reachable via reflog (or the remote's own reflog, for a force push) for a window
#     afterward, so an approval that lets the command through is not approving something
#     irreversible.
#
# `git checkout --` and `git restore` are two spellings of the same operation (git split
# checkout's overloaded roles in 2.23; restore is the current, recommended spelling) and must
# always land in the same tier - see BT-413. Do not add a new destructive command to either tier
# without updating the matching runtime hook.

set -u

# python3 is required to parse the JSON payload from the agent.
# If it is not available the hook exits non-zero so the agent treats this as a
# fail-closed event and blocks the triggering action rather than silently
# allowing it through.
if ! command -v python3 > /dev/null 2>&1; then
    MSG='Shell safety hook could not run: python3 is not installed. Install it or run `npx blit agents sync` to regenerate hooks.'
    # Without python3 we cannot detect the agent. Emit Cursor JSON on stdout (Cursor
    # failClosed) and a stderr reason + exit 2 (Claude PreToolUse block).
    printf '{"permission":"deny","user_message":"%s","agent_message":"%s"}\n' "$MSG" "$MSG"
    printf '%s\n' "$MSG" >&2
    exit 2
fi

INPUT_JSON="$(cat)"

# Detect Claude Code stdin (has hook_event_name or tool_name) vs Cursor.
IS_CLAUDE="$(printf '%s' "$INPUT_JSON" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    print('0')
    raise SystemExit(0)
print('1' if ('hook_event_name' in data or 'tool_name' in data) else '0')
")"

COMMAND_TEXT="$(printf '%s' "$INPUT_JSON" | python3 -c "
import json, sys

def walk(node):
    if isinstance(node, dict):
        for key in ('command', 'raw_command'):
            value = node.get(key)
            if isinstance(value, str) and value:
                return value
        for value in node.values():
            found = walk(value)
            if found:
                return found
    elif isinstance(node, list):
        for value in node:
            found = walk(value)
            if found:
                return found
    return ''

try:
    data = json.load(sys.stdin)
except Exception:
    print('')
    raise SystemExit(0)

print(walk(data))
")"

respond_allow() {
    if [ "$IS_CLAUDE" = "1" ]; then
        exit 0
    fi
    printf '{"permission":"allow"}\n'
    exit 0
}

respond_deny() {
    USER_MSG="$1"
    AGENT_MSG="$2"
    if [ "$IS_CLAUDE" = "1" ]; then
        # Exit 2 stderr is fed to the model, so use the agent-facing message.
        printf '%s\n' "$AGENT_MSG" >&2
        exit 2
    fi
    printf '{"permission":"deny","user_message":"%s","agent_message":"%s"}\n' "$USER_MSG" "$AGENT_MSG"
    exit 0
}

respond_ask() {
    USER_MSG="$1"
    AGENT_MSG="$2"
    if [ "$IS_CLAUDE" = "1" ]; then
        # permissionDecisionReason for "ask" is shown to the user in the permission UI.
        printf '%s\n' "$USER_MSG" | python3 -c "
import json, sys
reason = sys.stdin.read().rstrip('\n')
print(json.dumps({
    'hookSpecificOutput': {
        'hookEventName': 'PreToolUse',
        'permissionDecision': 'ask',
        'permissionDecisionReason': reason,
    }
}))
"
        exit 0
    fi
    printf '{"permission":"ask","user_message":"%s","agent_message":"%s"}\n' "$USER_MSG" "$AGENT_MSG"
    exit 0
}

if [ -z "$COMMAND_TEXT" ]; then
    respond_allow
fi

# Strip quote characters and backslashes before matching so a quoted or
# backslash-escaped subcommand (e.g. `git "reset" --hard`, `git \reset --hard`,
# `git push origin \+main`) cannot dodge the literal-word checks below -- the
# shell drops quotes and escaping backslashes at execution time and runs the
# same destructive command. This may over-match a literal multi-backslash
# sequence (e.g. `\\reset`, which the shell does not turn into `reset`), but
# that is a safe direction to err in for a security check.
NORMALIZED_TEXT="$(printf '%s' "$COMMAND_TEXT" | tr -d "'" | tr -d '"' | tr -d '\\')"

GIT_PREFIX='git([[:space:]]+(-[^[:space:]]+([[:space:]]+[^-][^[:space:]]*)?|--[^[:space:]]+([[:space:]]+[^-][^[:space:]]*)?))*[[:space:]]+'

# `git clean` deletes untracked files, so treat every invocation as destructive
# unless it is an explicit preview. Matching force flags alone was not enough:
# `git -c clean.requireForce=false clean -d` deletes without ever naming a force
# flag, and any other way around clean.requireForce would slip past the same way.
# So only a dry run (`-n`, `--dry-run`) that carries no force flag is allowed
# through; everything else, a bare `git clean` included, is denied. A preview
# that still bundles an f (`git clean -nfd`) is denied too: over-matching is the
# safe direction here, and the message says what to do instead. Each argument
# scan stops at a shell separator, so flags belonging to a later command
# (`git clean -n && rm -f build.log`) are never read as part of the clean.
GIT_CLEAN='clean([[:space:]]|[;&|<>]|$)'
GIT_CLEAN_FORCE='([[:space:]]+[^[:space:];&|<>]+)*[[:space:]]+(-[[:alnum:]]*f[[:alnum:]]*|--force)([[:space:]]|[;&|<>]|$)'
GIT_CLEAN_DRY_RUN='([[:space:]]+[^[:space:];&|<>]+)*[[:space:]]+(-[[:alnum:]]*n[[:alnum:]]*|--dry-run)([[:space:]]|[;&|<>]|$)'

# Exit status 0 when the command runs a `git clean` that is not a no-force dry run.
is_destructive_clean() {
    printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}${GIT_CLEAN}" || return 1
    printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}clean${GIT_CLEAN_FORCE}" && return 0
    printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}clean${GIT_CLEAN_DRY_RUN}" && return 1
    return 0
}

# `git restore` is the modern spelling of what `git checkout -- <path>` used to do, and must be
# gated the same way (BT-413). Every form touches the worktree and discards uncommitted changes
# with no recovery path, except `--staged`/`-S` given without `--worktree`/`-W`: that form only
# unstages, leaving the worktree file exactly as it was, so it is the one safe spelling.
GIT_RESTORE='restore([[:space:]]|[;&|<>]|$)'
GIT_RESTORE_STAGED='([[:space:]]+[^[:space:];&|<>]+)*[[:space:]]+(-S|--staged)([[:space:]]|[;&|<>]|$)'
GIT_RESTORE_WORKTREE='([[:space:]]+[^[:space:];&|<>]+)*[[:space:]]+(-W|--worktree)([[:space:]]|[;&|<>]|$)'

# Exit status 0 when the command runs a `git restore` that is not the staged-only safe form.
is_destructive_restore() {
    printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}${GIT_RESTORE}" || return 1
    printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}restore${GIT_RESTORE_STAGED}" || return 0
    printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}restore${GIT_RESTORE_WORKTREE}" && return 0
    return 1
}

if printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}reset[[:space:]]+--hard|${GIT_PREFIX}checkout[[:space:]]+--" || is_destructive_clean || is_destructive_restore; then
    respond_deny \
        'Blocked a destructive git command that could lose your game changes.' \
        'Use safer git operations. Ask the user before discarding any work.'
fi

# Require -f/--force/--force-with-lease to sit at an argument boundary
# (whitespace, a shell command separator such as ; & |, an unquoted
# redirection > or <, or end of line) so it does not match a substring inside
# a ref/branch name, e.g. `git push origin foo-feature` must not trip this.
# The shell splits an unquoted `--force>out` / `--force<in` into the argument
# `--force` plus a redirection with no whitespace needed, so > and < are
# argument boundaries too, same as ; & |. A refspec prefixed with `+` (e.g.
# `git push origin +main`) is git's other force-push spelling and is matched
# separately.
FORCE_FLAG='([[:space:]]+[^[:space:]]+)*[[:space:]]+(-f|--force|--force-with-lease(=[^[:space:]]*)?)([[:space:]]|[;&|<>]|$)'
FORCE_REFSPEC='([[:space:]]+[^[:space:]]+)*[[:space:]]+\+[^[:space:]]+'

if printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}push(${FORCE_FLAG}|${FORCE_REFSPEC})"; then
    respond_ask \
        'Force push detected. Confirm before continuing.' \
        'Force push rewrites history. Ask the user for explicit confirmation first.'
fi

# `git branch -D` permanently deletes an unmerged branch. The deleted commits stay reachable via
# reflog for a while (unlike reset --hard / checkout --/ restore / clean above), so this is "ask"
# rather than a hard block. `-D` is shorthand for `--delete --force`; scan for either spelling,
# including `-D` bundled with other short flags (e.g. `-Dq`).
GIT_BRANCH='branch([[:space:]]|[;&|<>]|$)'
GIT_BRANCH_SHORT_D='([[:space:]]+[^[:space:];&|<>]+)*[[:space:]]+-[[:alnum:]]*D[[:alnum:]]*([[:space:]]|[;&|<>]|$)'
GIT_BRANCH_LONG_DELETE='([[:space:]]+[^[:space:];&|<>]+)*[[:space:]]+--delete([[:space:]]|[;&|<>]|$)'
GIT_BRANCH_LONG_FORCE='([[:space:]]+[^[:space:];&|<>]+)*[[:space:]]+(-f|--force)([[:space:]]|[;&|<>]|$)'

# Exit status 0 when the command force-deletes a branch (`-D`, or `--delete` plus `--force`).
is_force_branch_delete() {
    printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}${GIT_BRANCH}" || return 1
    printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}branch${GIT_BRANCH_SHORT_D}" && return 0
    if printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}branch${GIT_BRANCH_LONG_DELETE}" \
        && printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}branch${GIT_BRANCH_LONG_FORCE}"; then
        return 0
    fi
    return 1
}

if is_force_branch_delete; then
    respond_ask \
        'Force branch delete detected (git branch -D). Confirm before continuing.' \
        'git branch -D permanently deletes an unmerged branch. Ask the user for explicit confirmation first.'
fi

# `git stash drop`/`git stash clear` permanently discards stashed work, but a stash entry is a
# commit object, so it stays reachable via reflog for a while - same "ask" tier as branch -D and
# force push, not a hard block.
GIT_STASH_DROP_CLEAR='stash[[:space:]]+(drop|clear)([[:space:]]|[;&|<>]|$)'

if printf '%s' "$NORMALIZED_TEXT" | grep -Eq "${GIT_PREFIX}${GIT_STASH_DROP_CLEAR}"; then
    respond_ask \
        'Stash drop/clear detected. Confirm before continuing.' \
        'git stash drop/clear permanently discards stashed work. Ask the user for explicit confirmation first.'
fi

respond_allow
